home/urls.py
from django.urls import path

from home.views import home

urlpatterns = [
    path('', home)
]

notes/urls.py
from django.urls import path

from notes import views

app_name = 'notes'

urlpatterns = [
    path('', views.home_page, name='home_page'),
    path('notes/search/', views.note_search, name='note_search'),
    path('notes/tags/<int:tag_id>', views.tag_page, name='tag_page'),
    path('notes/details/<int:note_id>', views.note_details,
         name='note_details'),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

notes/models.py
from django.contrib.auth.models import User
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return self.name


class Note(models.Model):
    slug = models.SlugField(unique=True)
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    page_cover = models.ImageField(
        upload_to='notes/page_covers/%Y/%m/%d/', blank=True, default='')
    card_cover = models.ImageField(
        upload_to='notes/card_covers/%Y/%m/%d/', blank=True, default='')
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)
    is_public = models.BooleanField(default=False)
    is_verified = models.BooleanField(default=False)
    is_published = models.BooleanField(default=False)
    is_content_html = models.BooleanField(default=False)

    def __str__(self):
        return self.title

home/views.py
from django.http import HttpResponse
from django.shortcuts import render


def home(request):
    return render(request, 'home/home.html', context={
        'name': 'Enzo Belém Farias',
    })

notes/views.py
from django.http import HttpResponse
from django.shortcuts import get_list_or_404, get_object_or_404, render

from .models import Note, Tag


def home_page(request):
    notes = Note.objects.filter(is_published=True).order_by('-id')
    return render(request, 'notes/pages/home.html', context={
        'notes': notes,
        'title': 'Home'
    })


def tag_page(request, tag_id):
    notes = get_list_or_404(
        Note.objects.filter(
            is_published=True,
            tags__id=tag_id
        ).order_by('-id')
    )
    tag_name = get_object_or_404(Tag, id=tag_id).name

    return render(request, 'notes/pages/home.html', context={
        'notes': notes,
        'title': f'Tag - {tag_name}'
    })


def note_details(request, note_id):
    note = get_object_or_404(
        Note.objects.filter(
            id=note_id
        ).order_by('-id')
    )
    return render(request, 'notes/pages/note_page.html', context={
        'note': note,
    })


def note_search(request):

    search_query = request.GET.get('q', '').strip()

    if not search_query:
        return HttpResponse(status=404)

    return render(request, 'notes/pages/search_page.html',
                  context={'title': 'Search',
                           'search_query': search_query})

notes/templates/notes/layout/empty_page.html
{% load static %}
<div class="empty_page_message">
    {% comment %} <div class="img-container">
        <img src="{% static 'notes/assets/img/doguinho_desconfiado.png' %}" alt="" class="image">
        <div class="image-text">já pensou em criar sua nota?</div>
    </div> {% endcomment %}
    <h1 class="h1">Nothing here.</h1>
    <h3 class="h4">how about create your notes?</h3>
</div>

notes/templates/notes/layout/footer.html
<footer class="text-white bg-dark">
    <div class="container p-3">
        <div class="row">
            <h1><i class="fa-solid fa-feather-pointed"></i> <i>Notes</i></h1>
        </div>
        <div class="foorter-info-page-author">
            <h3>Made with ❤ by <a href="https://github.com/EnzoBelem" target="__blank"><i>Enzo Belem</i></a></h3>
        </div>
    </div>
</footer>

notes/templates/notes/layout/head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Favicon -->
<link rel="icon" type="image/x-icon" href="{% static 'global/assets/img/feather-pointed-solid.svg' %}">
<!-- FontAwesome import -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/fontawesome.min.css"
    integrity="sha512-cHxvm20nkjOUySu7jdwiUxgGy11vuVPE9YeK89geLMLMMEOcKFyS2i+8wo0FOwyQO/bL8Bvq1KMsqK4bbOsPnA=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/brands.min.css"
    integrity="sha512-L+sMmtHht2t5phORf0xXFdTC0rSlML1XcraLTrABli/0MMMylsJi3XA23ReVQkZ7jLkOEIMicWGItyK4CAt2Xw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/solid.min.css"
    integrity="sha512-bdTSJB23zykBjGDvyuZUrLhHD0Rfre0jxTd0/jpTbV7sZL8DCth/88aHX0bq2RV8HK3zx5Qj6r2rRU/Otsjk+g=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
<!-- bootstrap import css -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<!-- google fonts -->
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
<!-- css styles -->
<link rel="stylesheet" href="{% static 'global/css/global_styles.css' %}">
<link rel="stylesheet" href="{% static 'notes/css/styles.css' %}">  

notes/templates/notes/layout/header.html
<header class="container-header">
    <div class="container">
        <nav class="page-header">
            <!-- logo section -->
            <div class="container-notes-brand">
                <a href="{% url 'notes:home_page'%}" class="notes-brand">
                    <h1><i class="fa-solid fa-feather-pointed"></i> <i>Notes</i></h1>
                </a>
                <h4 class="h4 notes-brand-text">Get organized, simple as a note.</h4>
            </div>
            <!-- dropdown section -->
            {% comment %} <div class="col-2 d-flex align-items-center justify-content-end">
                <div class="dropdown-center" style="font-size: xx-large;">
                    <a href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa-solid fa-bars"></i>
                    </a>
                    <ul class="dropdown-menu" style="font-size: large;">
                        <li>
                            <a class="dropdown-item d-flex align-items-center gap-3" href="#">
                                <i class="fa-solid fa-circle-user fa-2x"></i>
                                <span>{{ name }}</span>
                            </a>
                        </li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </div>
            </div> {% endcomment %}
        </nav>
    </div>
</header>

notes/templates/notes/layout/note_card.html
<div class="card-note-cell">
    <div class="card-note">
        <div class="card-image">
            {% if note.card_cover %}
            <img src="{{note.card_cover.url}}" alt="card-cover" class="card-img">
            {% endif %}
        </div>
        <div class="card-description">
            <h1 class="card-note-title">{{note.title}}</h1>
            <p>{{note.description}}</p>
            <!-- note infos -->
            <div class="card-info">
                <!-- creator info -->
                <div class="info-creator">
                    <i class="fa-solid fa-user"></i>
                    <span>{{note.author}}</span>
                </div>
                <!-- created_at info -->
                <div class="info-created-at">
                    <i class="fa-solid fa-calendar"></i>
                    <span>{{note.created_at|date:"d/m/Y"}} às {{note.created_at|date:"H:i"}}</span>
                </div>
                <!-- preview tags info-->
                <div class="info-tags">
                    {% if note.tags.all %}
                    <i class="fa-solid fa-tags"></i>
                    <div class="container-tags">
                        {% for tag in note.tags.all %}
                        <a href="{% url 'notes:tag_page' tag.id %}" class="tag">{{tag.name}}</a>
                        {% endfor %}
                    </div>
                    {% endif %}
                </div>
            </div>
            <!-- view more button -->
            <a class="card-view-more" href="{% url 'notes:note_details' note.id %}">
                <button>See more</button>
            </a>
        </div>
    </div>
</div>

notes/templates/notes/layout/note_details.html
{% comment %} <div class="card page-note">
    <!-- cover note -->
    <div class="card-header">
        <img src="{{note.cover.url}}" alt="note image">
    </div>
    <div class="card-body">
        <!-- title note -->
        <div class="row">
            <h1 class="page-note-title">{{note.title}}</h1>
        </div>
        <!-- content note -->
        <div class="row">
           <div class="col">
                <div class="page-note-content">
                    {% if note.is_content_html %}
                    {{note.content|safe}}
                    {% else %}
                    {{note.content|linebreaksbr}}
                    {% endif %}
                </div>
           </div>
        </div>
        <!-- infos note -->
        <div class="my-2 text-secondary page-note-infos">
            <!-- creator info -->
            <div class="info-creator">
                <i class="fa-solid fa-user fa-lg"></i>
                <span>{{note.author}}</span>
            </div>
            <!-- created_at info -->
            <div class="info-created-at">
                <i class="fa-solid fa-calendar fa-lg"></i>
                <span>{{note.created_at|date:"d/m/Y"}} às {{note.created_at|date:"H:i"}}</span>
            </div>
            <!-- preview tags info-->
            <div class="info-tags">
                <i class="fa-solid fa-tags fa-lg"></i>
                <div class="container-tags">
                    {% for tag in note.tags.all %}
                    <span class="tag">{{tag.name}}</span>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div> {% endcomment %}

<div class="page-note">    
    <div class="note-title-and-card">
        <div class="card-cover-container">
            {% if note.card_cover %}
            <img src="{{note.card_cover.url}}" alt="card cover">
            {% endif %}
        </div>
        <h1>{{note.title}}</h1>
    </div>
    <div class="page-content">
        {% if note.is_content_html %}
        {{note.content|safe}}
        {% else %}
        {{note.content|linebreaksbr}}
        {% endif %}
    </div>
    <div class="note-infos">
        <!-- creator info -->
        <div class="info-creator">
            <i class="fa-solid fa-user fa-lg"></i>
            <span>{{note.author}}</span>
        </div>
        <!-- created_at info -->
        <div class="info-created-at">
            <i class="fa-solid fa-calendar fa-lg"></i>
            <span>{{note.created_at|date:"d/m/Y"}} às {{note.created_at|date:"H:i"}}</span>
        </div>
        <!-- preview tags info-->
        <div class="info-tags">
            <i class="fa-solid fa-tags fa-lg"></i>
            <div class="container-tags">
                {% for tag in note.tags.all %}
                <span class="tag">{{tag.name}}</span>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

notes/templates/notes/layout/note_view.html
<div class="card page-note">
    <!-- cover note -->
    <div class="card-header">
        <img src="{{note.cover.url}}" alt="note image">
    </div>
    <div class="card-body">
        <!-- title note -->
        <div class="row">
            <h1 class="page-note-title">{{note.title}}</h1>
        </div>
        <!-- content note -->
        <div class="row">
           <div class="col">
                <div class="page-note-content">
                    {% if note.is_content_html %}
                    {{note.content|safe}}
                    {% else %}
                    {{note.content|linebreaksbr}}
                    {% endif %}
                </div>
           </div>
        </div>
        <!-- infos note -->
        <div class="my-2 text-secondary page-note-infos">
            <!-- creator info -->
            <div class="info-creator">
                <i class="fa-solid fa-user fa-lg"></i>
                <span>{{note.author}}</span>
            </div>
            <!-- created_at info -->
            <div class="info-created-at">
                <i class="fa-solid fa-calendar fa-lg"></i>
                <span>{{note.created_at|date:"d/m/Y"}} às {{note.created_at|date:"H:i"}}</span>
            </div>
            <!-- preview tags info-->
            <div class="info-tags">
                <i class="fa-solid fa-tags fa-lg"></i>
                <div class="container-tags">
                    {% for tag in note.tags.all %}
                    <span class="tag">{{tag.name}}</span>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

notes/templates/notes/layout/search_bar.html
<div class="container">
    <form action="{% url 'notes:note_search' %}" method="GET" class="search-form">
        <input type="search" name="q" id="input_serch" class="search-input" value="{{search_query}}" placeholder="Search for your notes" required>
        <button type="submit" class="search-button"><i class="fa-solid fa-magnifying-glass"></i></button>
    </form>
</div>

notes/templates/notes/pages/home.html
{% extends 'global/decorator.html' %}
{% load static %}
{% block title %}{{title}}{% endblock title %}
{% block serch_bar %}
    {% include 'notes/layout/search_bar.html' %}
{% endblock serch_bar %}
{% block content %}
    <div class="card-note-container">
        {% for note in notes %}
        {% include 'notes/layout/note_card.html' %}
        {% empty %}
        {% include 'notes/layout/empty_page.html' %}
    {% endfor %}
    </div>
{% endblock content %}
{% block scripts %}
    <script src="{% static 'notes/js/home.js' %}" type="module"></script>
{% endblock scripts %}

notes/templates/notes/pages/note_page.html
{% extends 'global/decorator.html' %}
{% block title %}Note Details{% endblock title %}
{% block note_page_cover %}
<div class="note-page-cover">
    {% if note.page_cover %}
    <img src="{{note.page_cover.url}}" alt="card-cover" class="card-img">
    {% endif %}
</div>
{% endblock note_page_cover %}
{% block content %}
    {% include 'notes/layout/note_details.html' %}
{% endblock content %}

notes/templates/notes/pages/note_view.html
{% extends 'global/decorator.html' %}
{% block title %}View Note |{% endblock title %}
{% block content %}
    {% include 'notes/layout/note_card.html' %}
{% endblock content %}

notes/templates/notes/pages/search_page.html
{% extends 'global/decorator.html' %}
{% load static %}
{% block title %}{{title}}{% endblock title %}
{% block serch_bar %}
    {% include 'notes/layout/search_bar.html' %}
{% endblock serch_bar %}
{% block content %}
    {% for note in notes %}
        <div class="card-note-container">
            {% include 'notes/layout/note_card.html' %}
        </div>
    {% empty %}
        {% include 'notes/layout/empty_page.html' %}
    {% endfor %}
{% endblock content %}
{% block scripts %}
    <script src="{% static 'notes/js/home.js' %}" type="module"></script>
{% endblock scripts %}